- hosts:
    - mdss
    - mons[0]
  gather_facts: false
  become: True
  any_errors_fatal: true
  vars:
    delegate_facts_host: True
  pre_tasks:
    - name: gather facts
      setup:
      when: not delegate_facts_host | bool

    - name: gather and delegate facts
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: True
      with_items:
        - "{{ groups['mons'] }}"
        - "{{ groups['mdss'] }}"
      run_once: True
      when: delegate_facts_host | bool

- hosts:
    - mdss
  gather_facts: false
  become: True
  any_errors_fatal: true
  vars:
    delegate_facts_host: True
  pre_tasks:
    - name: set ceph mds install 'In Progress'
      run_once: true
      set_stats:
        data:
          installer_phase_ceph_mds:
            status: "In Progress"
            start: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

  tasks:
    - import_role:
        name: ceph-defaults
      tags: ['ceph_update_config']
    - import_role:
        name: ceph-facts
      tags: ['ceph_update_config']
    - import_role:
        name: ceph-handler
    - import_role:
        name: ceph-common
    - import_role:
        name: ceph-config
      tags: ['ceph_update_config']
    - import_role:
        name: ceph-mds

  post_tasks:
    - name: set ceph mds install 'Complete'
      run_once: true
      set_stats:
        data:
          installer_phase_ceph_mds:
            status: "Complete"
            end: "{{ lookup('pipe', 'date +%Y%m%d%H%M%SZ') }}"

