---
# This playbook shrinks Ceph OSDs that have been created with ceph-volume.
# It can remove any number of OSD(s) from the cluster and ALL THEIR DATA
#
# Use it like this:
# ansible-playbook shrink-osd.yml -e osd_to_kill=0,2,6
#     Prompts for confirmation to shrink, defaults to no and
#     doesn't shrink the cluster. yes shrinks the cluster.
#
# ansible-playbook -e ireallymeanit=yes|no shrink-osd.yml
#     Overrides the prompt using -e option. Can be used in
#     automation scripts to avoid interactive prompt.

- name: gather facts and check the init system
  hosts:
    - "{{ mon_group_name|default('mons') }}"
    - "{{ osd_group_name|default('osds') }}"
  become: True
  tasks:
    - debug: msg="gather facts on all Ceph hosts for following reference"


- hosts: osds
  become: true
  pre_tasks:
    - name: get osd numbers
      shell: "if [ -d /var/lib/ceph/osd ] ; then ls /var/lib/ceph/osd | sed 's/.*-//' ; fi"
      register: osd_ids
      changed_when: false

    - set_fact:
        osd_id_list: "{{ osd_ids.stdout_lines | join(',') }}"

  tasks:
    - debug: var=osd_id_list


- hosts: localhost
  become: true
  vars:
    mon_group_name: mons
    osd_group_name: osds
  tasks:
    - set_fact:
        osd_to_kill: "{{ osd_to_kill|default('') + hostvars[item]['osd_id_list'] }},"
      with_items:
        - "{{ groups['osds'] }}"

    - set_fact:
        osd_to_kill: "{{ osd_to_kill[:-1] }}"

    - debug: msg="{{ osd_to_kill }}"

    - name: exit playbook, if no osd(s) was/were given
      fail:
        msg: "osd_to_kill must be declared
          Exiting shrink-osd playbook, no OSD(s) was/were removed.
           On the command line when invoking the playbook, you can use
           -e osd_to_kill=0,1,2,3 argument."
      when: osd_to_kill is not defined

    - import_role:
        name: ceph-defaults

    - import_role:
        name: ceph-facts

  post_tasks:
    - name: set_fact container_exec_cmd build docker exec command (containerized)
      set_fact:
        container_exec_cmd: "{{ container_binary }} exec ceph-mon-{{ hostvars[groups[mon_group_name][0]]['ansible_hostname'] }}"
      when: containerized_deployment | bool

    - name: exit playbook, if can not connect to the cluster
      command: "{{ container_exec_cmd }} timeout 5 ceph --cluster {{ cluster }} health"
      register: ceph_health
      until: ceph_health.stdout.find("HEALTH") > -1
      delegate_to: "{{ groups[mon_group_name][0] }}"
      retries: 5
      delay: 2

    - name: find the host(s) where the osd(s) is/are running on
      command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} osd find {{ item }}"
      with_items: "{{ osd_to_kill.split(',') }}"
      delegate_to: "{{ groups[mon_group_name][0] }}"
      register: find_osd_hosts

    - name: set_fact osd_hosts
      set_fact:
        osd_hosts: "{{ osd_hosts | default([]) + [ [ (item.stdout | from_json).host, (item.stdout | from_json).osd_fsid ] ] }}"
      with_items: "{{ find_osd_hosts.results }}"

    - name: mark osd(s) out of the cluster
      command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} osd out {{ osd_to_kill.replace(',', ' ') }}"
      run_once: true
      delegate_to: "{{ groups[mon_group_name][0] }}"

    - name: stop osd(s) service
      service:
        name: ceph-osd@{{ item.0 }}
        state: stopped
        enabled: no
      loop: "{{ osd_to_kill.split(',')|zip(osd_hosts)|list }}"
      delegate_to: "{{ item.1.0 }}"

    - name: zap osd devices
      ceph_volume:
        action: "zap"
        osd_fsid: "{{ item.1 }}"
      environment:
        CEPH_VOLUME_DEBUG: 1
        CEPH_CONTAINER_IMAGE: "{{ ceph_docker_registry + '/' + ceph_docker_image + ':' + ceph_docker_image_tag if containerized_deployment else None }}"
        CEPH_CONTAINER_BINARY: "{{ container_binary }}"
      delegate_to: "{{ item.0 }}"
      loop: "{{ osd_hosts }}"

    - name: purge osd(s) from the cluster
      command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} osd purge {{ item }} --yes-i-really-mean-it"
      run_once: true
      delegate_to: "{{ groups[mon_group_name][0] }}"
      with_items: "{{ osd_to_kill.split(',') }}"

    - name: remove osd(s) from the crushmap
      command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} osd crush rm {{ item }}"
      run_once: true
      delegate_to: "{{ groups[mon_group_name][0] }}"
      with_items: "{{ groups[osd_group_name] }}"

    - name: show ceph health
      command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} -s"
      delegate_to: "{{ groups[mon_group_name][0] }}"

    - name: show ceph osd tree
      command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} osd tree"
      delegate_to: "{{ groups[mon_group_name][0] }}"