---
- name: create bootstrap-mds and mds directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
    group: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
    mode: "0755"
  with_items:
    - /var/lib/ceph/bootstrap-mds/
    - /var/lib/ceph/mds/{{ cluster }}-{{ mds_name }}

- include_tasks: "{{ playbook_dir }}/copy-keyring-mds.yml"

