---
- name: check if ceph filesystem already exists
  command: "{{ container_exec_cmd | default('') }} ceph --cluster {{ cluster }} fs get {{ cephfs_name }}"
  register: check_existing_cephfs
  changed_when: false
  failed_when: false

- name: clean metadata pool
  command: "rados purge {{ cephfs_metadata_pool }} --yes-i-really-really-mean-it"
  changed_when: false
  failed_when: false

- name: sleep
  command: "sleep 5"

- name: create ceph filesystem
  command: "{{ container_exec_cmd | default('') }} ceph --cluster {{ cluster }} fs new {{ cephfs_name }} {{ cephfs_metadata_pool }} {{ cephfs_default_data_pool }}"
  changed_when: false
  when: check_existing_cephfs.rc != 0

- name: check if ceph filesystem already exists
  command: "{{ container_exec_cmd | default('') }} ceph --cluster {{ cluster }} fs get {{ cephfs_name }}"
  register: check_existing_cephfs
  changed_when: false
  failed_when: false

- name: add data pools to existing fs
  command: "{{ container_exec_cmd | default('') }} ceph fs add_data_pool {{ cephfs_name }} {{ item }}"
  changed_when: false
  with_items:
    - "{{ cephfs_data_pool_list }}"
  when: (check_existing_cephfs.rc == 0) and (cephfs_data_pool_list is defined)
